# Generated by Django 3.1.1 on 2020-09-08 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
