# Generated by Django 3.1.1 on 2020-09-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200916_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='compression_ratio',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='original_text',
            field=models.TextField(default=''),
        ),
    ]
